name: Add menu placeholders

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 1"

permissions:
  contents: write

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install deps
        run: python -m pip install --upgrade pip

      - name: Dry run (see what would change)
        run: |
          python scripts/maint/add_menu_placeholders.py \
            --file bestmuscat-new-main/data/tools.json || true

      - name: Apply changes
        run: |
          python scripts/maint/add_menu_placeholders.py \
            --file bestmuscat-new-main/data/tools.json --write

      - name: Commit & push (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add bestmuscat-new-main/data/tools.json
          git diff --cached --quiet || git commit -m "chore: add menu placeholders"
          git push
